//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 02:20:57 PM SGT 
//


package drg.drgclaimsubmission.utilities.dtd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drgclaim"
})
@XmlRootElement(name = "CF5")
public class CF5 {

    @XmlAttribute(name = "pHospitalCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pHospitalCode;
    @XmlElement(name = "DRGCLAIM")
    protected List<DRGCLAIM> drgclaim;

    /**
     * Gets the value of the pHospitalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHospitalCode() {
        return pHospitalCode;
    }

    /**
     * Sets the value of the pHospitalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHospitalCode(String value) {
        this.pHospitalCode = value;
    }

    /**
     * Gets the value of the drgclaim property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drgclaim property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDRGCLAIM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DRGCLAIM }
     * 
     * 
     */
    public List<DRGCLAIM> getDRGCLAIM() {
        if (drgclaim == null) {
            drgclaim = new ArrayList<DRGCLAIM>();
        }
        return this.drgclaim;
    }

}
