//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 02:20:57 PM SGT 
//


package drg.drgclaimsubmission.utilities.dtd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secondarydiagsOrPROCEDURES"
})
@XmlRootElement(name = "DRGCLAIM")
public class DRGCLAIM {

    @XmlAttribute(name = "ClaimNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String claimNumber;
    @XmlAttribute(name = "PrimaryCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primaryCode;
    @XmlAttribute(name = "NewBornAdmWeight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String newBornAdmWeight;
    @XmlAttribute(name = "Remarks")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String remarks;
    @XmlElements({
        @XmlElement(name = "SECONDARYDIAGS", type = SECONDARYDIAGS.class),
        @XmlElement(name = "PROCEDURES", type = PROCEDURES.class)
    })
    protected List<Object> secondarydiagsOrPROCEDURES;

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the primaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryCode() {
        return primaryCode;
    }

    /**
     * Sets the value of the primaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryCode(String value) {
        this.primaryCode = value;
    }

    /**
     * Gets the value of the newBornAdmWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBornAdmWeight() {
        return newBornAdmWeight;
    }

    /**
     * Sets the value of the newBornAdmWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBornAdmWeight(String value) {
        this.newBornAdmWeight = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the secondarydiagsOrPROCEDURES property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondarydiagsOrPROCEDURES property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECONDARYDIAGSOrPROCEDURES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECONDARYDIAGS }
     * {@link PROCEDURES }
     * 
     * 
     */
    public List<Object> getSECONDARYDIAGSOrPROCEDURES() {
        if (secondarydiagsOrPROCEDURES == null) {
            secondarydiagsOrPROCEDURES = new ArrayList<Object>();
        }
        return this.secondarydiagsOrPROCEDURES;
    }

}
