//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 02:20:57 PM SGT 
//


package drg.drgclaimsubmission.utilities.dtd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }
    /**
     * Create an instance of {@link PROCEDURES }
     * 
     * @return 
     */
    public PROCEDURES createPROCEDURES() {
        return new PROCEDURES();
    }

    /**
     * Create an instance of {@link PROCEDURE }
     * 
     * @return 
     */
    public PROCEDURE createPROCEDURE() {
        return new PROCEDURE();
    }

    /**
     * Create an instance of {@link CF5 }
     * 
     * @return 
     */
    public CF5 createCF5() {
        return new CF5();
    }

    /**
     * Create an instance of {@link DRGCLAIM }
     * 
     * @return 
     */
    public DRGCLAIM createDRGCLAIM() {
        return new DRGCLAIM();
    }

    /**
     * Create an instance of {@link SECONDARYDIAGS }
     * 
     * @return 
     */
    public SECONDARYDIAGS createSECONDARYDIAGS() {
        return new SECONDARYDIAGS();
    }

    /**
     * Create an instance of {@link SECONDARYDIAG }
     * 
     * @return 
     */
    public SECONDARYDIAG createSECONDARYDIAG() {
        return new SECONDARYDIAG();
    }

}
