//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 02:20:57 PM SGT 
//


package drg.drgclaimsubmission.utilities.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PROCEDURE")
public class PROCEDURE {

    @XmlAttribute(name = "RvsCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rvsCode;
    @XmlAttribute(name = "Laterality")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String laterality;
    @XmlAttribute(name = "Ext1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ext1;
    @XmlAttribute(name = "Ext2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ext2;
    @XmlAttribute(name = "Remarks")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String remarks;

    /**
     * Gets the value of the rvsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRvsCode() {
        return rvsCode;
    }

    /**
     * Sets the value of the rvsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRvsCode(String value) {
        this.rvsCode = value;
    }

    /**
     * Gets the value of the laterality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaterality() {
        return laterality;
    }

    /**
     * Sets the value of the laterality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaterality(String value) {
        this.laterality = value;
    }

    /**
     * Gets the value of the ext1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * Sets the value of the ext1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExt1(String value) {
        this.ext1 = value;
    }

    /**
     * Gets the value of the ext2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * Sets the value of the ext2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExt2(String value) {
        this.ext2 = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

}
