//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 02:20:57 PM SGT 
//


package drg.drgclaimsubmission.utilities.dtd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secondarydiag"
})
@XmlRootElement(name = "SECONDARYDIAGS")
public class SECONDARYDIAGS {

    @XmlElement(name = "SECONDARYDIAG")
    protected List<SECONDARYDIAG> secondarydiag;

    /**
     * Gets the value of the secondarydiag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondarydiag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECONDARYDIAG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECONDARYDIAG }
     * 
     * 
     */
    public List<SECONDARYDIAG> getSECONDARYDIAG() {
        if (secondarydiag == null) {
            secondarydiag = new ArrayList<SECONDARYDIAG>();
        }
        return this.secondarydiag;
    }

}
