//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.22 at 03:15:14 PM SGT 
//


package drg.drgclaimsubmission.structures.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drgclaim"
})
@XmlRootElement(name = "CF5")
public class CF5 {

    @XmlAttribute(name = "pHospitalCode", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pHospitalCode;
    @XmlElement(name = "DRGCLAIM", required = true)
    protected DRGCLAIM drgclaim;

    /**
     * Gets the value of the pHospitalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHospitalCode() {
        return pHospitalCode;
    }

    /**
     * Sets the value of the pHospitalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHospitalCode(String value) {
        this.pHospitalCode = value;
    }

    /**
     * Gets the value of the drgclaim property.
     * 
     * @return
     *     possible object is
     *     {@link DRGCLAIM }
     *     
     */
    public DRGCLAIM getDRGCLAIM() {
        return drgclaim;
    }

    /**
     * Sets the value of the drgclaim property.
     * 
     * @param value
     *     allowed object is
     *     {@link DRGCLAIM }
     *     
     */
    public void setDRGCLAIM(DRGCLAIM value) {
        this.drgclaim = value;
    }

}
