//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.22 at 03:15:14 PM SGT 
//


package drg.drgclaimsubmission.structures.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secondarydiags",
    "procedures"
})
@XmlRootElement(name = "DRGCLAIM")
public class DRGCLAIM {

    @XmlAttribute(name = "ClaimNumber", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String claimNumber;
    @XmlAttribute(name = "PrimaryCode", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primaryCode;
    @XmlAttribute(name = "NewBornAdmWeight", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String newBornAdmWeight;
    @XmlAttribute(name = "Remarks", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String remarks;
    @XmlElement(name = "SECONDARYDIAGS", required = true)
    
    protected SECONDARYDIAGS secondarydiags;
    @XmlElement(name = "PROCEDURES", required = true)
    protected PROCEDURES procedures;

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the primaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryCode() {
        return primaryCode;
    }

    /**
     * Sets the value of the primaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryCode(String value) {
        this.primaryCode = value;
    }

    /**
     * Gets the value of the newBornAdmWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBornAdmWeight() {
        return newBornAdmWeight;
    }

    /**
     * Sets the value of the newBornAdmWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBornAdmWeight(String value) {
        this.newBornAdmWeight = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the secondarydiags property.
     * 
     * @return
     *     possible object is
     *     {@link SECONDARYDIAGS }
     *     
     */
    public SECONDARYDIAGS getSECONDARYDIAGS() {
        return secondarydiags;
    }

    /**
     * Sets the value of the secondarydiags property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECONDARYDIAGS }
     *     
     */
    public void setSECONDARYDIAGS(SECONDARYDIAGS value) {
        this.secondarydiags = value;
    }

    /**
     * Gets the value of the procedures property.
     * 
     * @return
     *     possible object is
     *     {@link PROCEDURES }
     *     
     */
    public PROCEDURES getPROCEDURES() {
        return procedures;
    }

    /**
     * Sets the value of the procedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROCEDURES }
     *     
     */
    public void setPROCEDURES(PROCEDURES value) {
        this.procedures = value;
    }

}
